apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.42
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '1234'
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql # Mount path inside the container
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - image: mysql:5.7.42
#           name: mysql
#           env:
#             # Use secret in real usage
#             - name: MYSQL_ROOT_PASSWORD
#               value: 'password'
#             - name: MYSQL_DATABASE
#               value: test
#           ports:
#             - containerPort: 3306
#               name: mysql
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#             - name: mysql-initdb
#               mountPath: /docker-entrypoint-initdb.d
#       volumes:
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: mysql-pv-claim
#         - name: mysql-initdb
#           configMap:
#             name: mysql-initdb-config
#           #hostPath:
#           #path: /pathonhost/
#           #type: Directory
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-clusterip-srv
# spec:
#   selector:
#     app: mysql
#   ports:
#     - name: mysql
#       protocol: TCP
#       port: 3306
#       targetPort: 3306
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-initdb-config
# data:
#   initdb.sql: CREATE TABLE `users` (`id` int(11) NOT NULL, `name` varchar(255) DEFAULT NULL, `email` varchar(255) DEFAULT NULL, `address` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
